/**
 * migrate.ts — the one command that changes database schema.
 *
 * Applies `migrations/` in journal order, inside a transaction per migration,
 * recording each in `schema_migrations`. It is never imported by the server:
 * boot does no DDL (#24), and ADR-0016 runs this as a gated pre-deploy step.
 *
 *   npm run db:migrate                 apply everything pending
 *   npm run db:migrate:status          list applied and pending, change nothing
 *   npm run db:migrate -- --dry-run    print what would run, change nothing
 *   npm run db:migrate -- --baseline 0002_slimy_whirlwind
 *                                      record 0000..0002 as applied without
 *                                      running them, then apply the rest
 *
 * `--status` and `--dry-run` change nothing at all, including the ledger: they
 * read what is recorded and create nothing that is not already there, so either
 * is safe to point at a database you are only asking about.
 *
 * `applyThrough` is a function option (not a CLI flag): apply up to a named
 * version and leave later entries pending. The workspace-seed suite uses it so
 * fixture users exist before the mapping SQL runs.
 *
 * `--baseline` exists for the databases that predate this journal. Production
 * was built with `drizzle-kit push` and has no migration record at all, so a
 * first run here would try to `CREATE TABLE` over live tables. Baseline it at
 * the last migration its schema already contains, once, and every deploy after
 * that is an ordinary `db:migrate`.
 *
 * Plain `pg` and plain SQL, no Neon-specific features (ADR-0016), and no import
 * of `server/config.ts` — see `scripts/lib/db.ts` for why.
 */

import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";
import { requireDatabaseUrl } from "../shared/databaseUrl";
import type { Report } from "./lib/db";
import { isEntryPoint } from "./lib/entrypoint";

const MIGRATIONS_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "migrations");

/** Drizzle writes this between statements; it is also a valid SQL comment. */
const STATEMENT_BREAKPOINT = "--> statement-breakpoint";

const LEDGER_TABLE = "schema_migrations";

interface Migration {
  /** The file's tag, e.g. `0003_vector_embeddings` — the `schema_migrations` key. */
  version: string;
  sql: string;
  checksum: string;
}

interface AppliedMigration {
  version: string;
  checksum: string;
}

/**
 * The journal, in order. `migrations/meta/_journal.json` is drizzle-kit's own
 * index and the single ordering authority: a `.sql` file that is not in it was
 * not generated by `drizzle-kit generate` and is not part of the journal, so it
 * is never run rather than silently picked up by a directory listing.
 */
export function loadMigrations(): Migration[] {
  const journalPath = join(MIGRATIONS_DIR, "meta", "_journal.json");
  const journal = JSON.parse(readFileSync(journalPath, "utf8")) as {
    entries: { idx: number; tag: string }[];
  };

  return [...journal.entries]
    .sort((a, b) => a.idx - b.idx)
    .map(({ tag }) => {
      const sql = readFileSync(join(MIGRATIONS_DIR, `${tag}.sql`), "utf8");
      return {
        version: tag,
        sql,
        checksum: createHash("sha256").update(sql).digest("hex"),
      };
    });
}

/**
 * The ledger. `applied_at` and `execution_ms` are for the migration evidence
 * ADR-0017 asks each phase to leave behind; `checksum` is what catches a file
 * edited after it shipped, when the database can no longer be made to match it.
 */
async function ensureLedger(client: pg.Client): Promise<void> {
  await client.query(`
    CREATE TABLE IF NOT EXISTS ${LEDGER_TABLE} (
      version      text PRIMARY KEY,
      checksum     text        NOT NULL,
      applied_at   timestamptz NOT NULL DEFAULT now(),
      execution_ms integer     NOT NULL DEFAULT 0,
      baselined    boolean     NOT NULL DEFAULT false
    );
  `);
}

/**
 * What the database records as applied. A database with no ledger table has
 * nothing applied, which is the honest answer for the read-only modes — they
 * must not create the table just to find it empty.
 */
async function readLedger(client: pg.Client): Promise<Map<string, AppliedMigration>> {
  const { rows: existence } = await client.query<{ present: boolean }>(
    `SELECT to_regclass('public.${LEDGER_TABLE}') IS NOT NULL AS present`
  );
  if (!existence[0]?.present) return new Map();

  const { rows } = await client.query<AppliedMigration>(
    `SELECT version, checksum FROM ${LEDGER_TABLE}`
  );
  return new Map(rows.map((row) => [row.version, row]));
}

/**
 * Refuse to run when a migration already applied no longer matches its file.
 * The database cannot be brought back in line by re-running it, so the only
 * safe move is to stop and let a human decide — usually by adding a new
 * migration rather than editing a shipped one.
 */
function assertNoDrift(migrations: Migration[], applied: Map<string, AppliedMigration>): void {
  const drifted = migrations.filter(
    (migration) =>
      applied.has(migration.version) && applied.get(migration.version)!.checksum !== migration.checksum
  );
  if (drifted.length === 0) return;

  throw new Error(
    `Applied migrations no longer match their files:\n` +
      drifted.map((migration) => `  ${migration.version}`).join("\n") +
      `\n\nA migration is immutable once applied. Add a new one instead of editing it.`
  );
}

/**
 * Split on drizzle's breakpoint marker so a failure names the statement that
 * failed. Hand-written files without the marker run as one multi-statement
 * batch, which Postgres accepts and the surrounding transaction still covers.
 */
function statementsOf(migration: Migration): string[] {
  return migration.sql
    .split(STATEMENT_BREAKPOINT)
    .map((statement) => statement.trim())
    .filter((statement) => statement.length > 0);
}

async function applyMigration(client: pg.Client, migration: Migration): Promise<number> {
  const started = Date.now();
  await client.query("BEGIN");
  try {
    for (const statement of statementsOf(migration)) {
      await client.query(statement);
    }
    const elapsed = Date.now() - started;
    await client.query(
      `INSERT INTO ${LEDGER_TABLE} (version, checksum, execution_ms) VALUES ($1, $2, $3)`,
      [migration.version, migration.checksum, elapsed]
    );
    await client.query("COMMIT");
    return elapsed;
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  }
}

function indexOfVersion(migrations: Migration[], version: string): number {
  const at = migrations.findIndex((migration) => migration.version === version);
  if (at === -1) {
    throw new Error(
      `No migration named "${version}". The journal holds:\n` +
        migrations.map((migration) => `  ${migration.version}`).join("\n")
    );
  }
  return at;
}

/** The migrations `--baseline <version>` covers that are not already recorded. */
function migrationsToBaseline(
  migrations: Migration[],
  applied: Map<string, AppliedMigration>,
  through: string
): Migration[] {
  const last = indexOfVersion(migrations, through);
  return migrations.slice(0, last + 1).filter((migration) => !applied.has(migration.version));
}

async function recordBaseline(client: pg.Client, migrations: Migration[]): Promise<void> {
  await client.query("BEGIN");
  try {
    for (const migration of migrations) {
      await client.query(
        `INSERT INTO ${LEDGER_TABLE} (version, checksum, baselined) VALUES ($1, $2, true)
         ON CONFLICT (version) DO NOTHING`,
        [migration.version, migration.checksum]
      );
    }
    await client.query("COMMIT");
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  }
}

interface Options {
  status: boolean;
  dryRun: boolean;
  /** Migrations up to and including this version are recorded, not run. */
  baselineThrough?: string;
  /** Apply up to and including this version; leave later entries pending. */
  applyThrough?: string;
}

function parseArgs(argv: string[]): Options {
  const options: Options = { status: argv.includes("--status"), dryRun: argv.includes("--dry-run") };

  const baselineAt = argv.indexOf("--baseline");
  if (baselineAt !== -1) {
    const version = argv[baselineAt + 1];
    if (!version || version.startsWith("--")) {
      throw new Error("--baseline needs the version to baseline through, e.g. --baseline 0002_slimy_whirlwind");
    }
    options.baselineThrough = version;
  }

  return options;
}

/**
 * Applies the journal against `url` and returns the versions it ran. Exported
 * so the test harness builds its database the way a deploy does, rather than
 * through a second mechanism that could drift from this one.
 */
export async function migrate(
  url: string,
  options: Partial<Options> = {},
  report: Report = () => {}
): Promise<string[]> {
  const migrations = loadMigrations();
  // The two modes that promise to change nothing. Everything below that would
  // write — creating the ledger, recording a baseline, applying a migration —
  // is gated on this, so either mode is safe against a database you are only
  // asking about.
  const readOnly = options.status === true || options.dryRun === true;

  const client = new pg.Client({ connectionString: url });
  await client.connect();

  try {
    if (!readOnly) await ensureLedger(client);
    const applied = await readLedger(client);
    assertNoDrift(migrations, applied);

    if (options.baselineThrough) {
      const toRecord = migrationsToBaseline(migrations, applied, options.baselineThrough);
      if (!readOnly) await recordBaseline(client, toRecord);
      for (const migration of toRecord) {
        report(
          readOnly
            ? `would baseline ${migration.version} (record, not run)`
            : `baselined ${migration.version} (recorded, not run)`
        );
        // Counted as applied for the rest of this run, so `--status` and
        // `--dry-run` describe the database a real run would leave behind.
        applied.set(migration.version, migration);
      }
    }

    const applyThroughAt = options.applyThrough
      ? indexOfVersion(migrations, options.applyThrough)
      : migrations.length - 1;

    const pending = migrations.filter(
      (migration, at) => !applied.has(migration.version) && at <= applyThroughAt
    );

    if (options.status) {
      for (const migration of migrations) {
        report(`${applied.has(migration.version) ? "applied" : "pending"}  ${migration.version}`);
      }
      return [];
    }

    if (pending.length === 0) {
      report("no pending migrations");
      return [];
    }

    if (options.dryRun) {
      for (const migration of pending) {
        report(`would apply ${migration.version} (${statementsOf(migration).length} statements)`);
      }
      return [];
    }

    const ran: string[] = [];
    for (const migration of pending) {
      const elapsed = await applyMigration(client, migration);
      report(`applied ${migration.version} in ${elapsed}ms`);
      ran.push(migration.version);
    }
    return ran;
  } finally {
    await client.end();
  }
}

if (isEntryPoint(import.meta.url)) {
  const options = parseArgs(process.argv.slice(2));
  migrate(requireDatabaseUrl(), options, (message) => console.log(message)).catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
